# Created by Jekyll Writer
title: 于成
author: 于成学习笔记
description: >
  河北银行友南支行
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: aceo
github_username: hebbank
markdown: kramdown
baseurl: /jekyll
