# Created by Jekyll Writer
title: 图批金融
author: pos
description: >
  图批金融
permalink: '/:year/:month/:day/:title/'
paginate: 6
paginate_path: '/page/:num/'
twitter_username: aceo
github_username: hebbank
markdown: kramdown
baseurl: /jekyll
